const express = require("express")
const router = express.Router()
const controllers= require("../controllers/RestaurantController")

router.route("/signup")
        .post(controllers.signupRestaurant)
router.route("/login")
        .post(controllers.loginRestaurant)
router.route("/dashboard")
      .get(controllers.showDashboard)
router.route("/isopen/:restaurantId")
      .put(controllers.toggleRestaurantOpen)
router.route("/foods")
      .get(controllers.getAllFood)
router.route("/addfood")
      .post(controllers.addFood)
router.route("/deletefood/:foodId")
      .delete(controllers.deleteFood)
router.route("/editfood/:foodId")
      .put(controllers.editFood)
router.route("/fooditems/stockout/:foodId")
      .put(controllers.stockoutToggle)
router.route("/updateStock/:foodId/:restaurantId")
      .put(controllers.updateStock)
module.exports = router;